// Auto-generated barrel file
export * from './test-phase2-quick.js';
export * from './components/index.js';
export * from './config/index.js';
export * from './contexts/index.js';
export * from './core/index.js';
export * from './data/index.js';
export * from './database/index.js';
export * from './examples/index.js';
export * from './hooks/index.js';
export * from './organizacao/index.js';
export * from './services/index.js';
export * from './styles/index.js';
export * from './tests/index.js';
export * from './utils/index.js';
